server:
  port: 0
  
kafka:
  bootstrap:
    servers: localhost:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

datasource:
  db_lastmile:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lastmile
    username: postgres
    password: root
  db_workflow:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/delivery_workflow
    username: postgres
    password: root
  jpa:
   show-sql: false
   database: default
   hibernate:
     use-new-id-generator-mappings: false
   open-in-view: false   
  
spring:
  application:
    name: DELIVERYWORKFLOW
  couchbase:
    bootstrap-hosts: localhost
    bucket:
      name: vehicle_tracking
  data:
    couchbase:
      auto-index: true
 

oauth2:
  tokenServiceEndpointUrl: http://localhost:60700/u/oauth/check_token
  clientId: WEB
  clientSecret: WEB  
