eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    
server:
  port: 0
  
oauth2:
  tokenServiceEndpointUrl: http://localhost:60700/u/oauth/check_token
  clientId: ANDROID
  clientSecret: ANDROID   
  
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lastmile
    username: postgres
    password: root
  application:
    name: PACKAGES
  jpa:
    show-sql: true
    database: default

kafka:
  bootstrap:
    servers: localhost:9092 
jsondoc:
  version:
      1.0
  basePath:
      /packages
  packages[0]:
      com.appzoneltd.lastmile.microservice.packge.controller
  packages[1]:
      com.appzoneltd.lastmile.microservice.packge.dao   
