eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 0
 
spring:
  application:
     name: PACKAGEWEIGHT
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lastmile
    username: postgres
    password: root
    test-while-idle: true
    validation-query: SELECT 1


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    cassandra:
#      contact-points: 192.168.1.105
#      port: 9042
      keyspace-name: lastmile
        
        
oauth2:
  tokenServiceEndpointUrl: http://localhost:60700/u/oauth/check_token
  clientId: WEB
  clientSecret: WEB    
    