eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

jsondoc:
  version:
      1.0
  basePath:
      /configuration
  packages[0]:
      com.appzoneltd.lastmile.microservice.SystemConfig.controller
  packages[1]:
      com.appzoneltd.lastmile.microservice.SystemConfig.dao      
          
server:
  port: 0
  
  
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lastmile
    username: postgres
    password: root
  data:
      cassandra:
        keyspace-name: lastmile
#        port: 9042
#        contact-points: 192.168.1.105
  application:
    name: SYSTEMCONFIGURATION


oauth2:
  tokenServiceEndpointUrl: http://localhost:60700/u/oauth/check_token
  clientId: WEB
  clientSecret: WEB   
  
kafka:
  bootstrap:
    servers: localhost:9092          