eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    
#security:
#  basic:
#    enabled: false
#  oauth2:
#    resource:
#      userInfoUri: http://localhost:8080/u/user    
    
    
    
jsondoc:
  version: 1.0
  basePath: /vehicleregister
  packages[0]: com.appzoneltd.lastmile.microservice.vehicleregistration.controller
  packages[1]: com.appzoneltd.lastmile.microservice.vehicleregistration.dao
  
server:
  port: 10590
  
spring:
  application:
    name: VEHICLEREGISTRATION
  datasource:
    url: jdbc:postgresql://localhost:5432/lastmile
    username: postgres
    password: root
  jpa:
   show-sql: false
   database: default 
   hibernate:
     use-new-id-generator-mappings: false
   open-in-view: false
  couchbase:
    bootstrap-hosts: localhost
    bucket:
      name: vehicle_tracking
  data:
    couchbase:
      auto-index: true

oauth2:
  tokenServiceEndpointUrl: http://localhost:60701/d/oauth/check_token
  clientId: DRIVER
  clientSecret: DRIVER      
  
logging:
  file: VehicleRegistration.log
