eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 0
 
oauth2:
  tokenServiceEndpointUrl: http://localhost:60700/u/oauth/check_token
  clientId: WEB
  clientSecret: WEB  
  
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lastmile
    username: postgres
    password: root
  application:
    name: CALENDAR
  data:
    cassandra:
      keyspace-name: lastmile
#      contact-points: 192.168.1.105
#      port: 9042

    
logging:
  file: Calendar.log
    
jsondoc:
  version:
      1.0
  basePath:
      /calendar
  packages[0]:
      com.appzoneltd.lastmile.microservice.calendar.controller
  packages[1]:
      com.appzoneltd.lastmile.microservice.calendar.dao     
          
