/*
 * Created on 3 Jul 2017 ( Time 14:38:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.appzoneltd.lastmile.authorizationserver.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import lombok.Data;

@Data
@Entity
@Table(name = "users", schema = "lastmile_authorization_server")
public class UserEntity implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "user_id", nullable = false)
	private Long userId;

	@Column(name = "username", length = 100)
	private String username;

	@Column(name = "password", nullable = false, length = 100)
	private String password;

	@Column(name = "firstname", nullable = false, length = 100)
	private String firstname;

	@Column(name = "lastname", nullable = false, length = 100)
	private String lastname;

	@Column(name = "phone", nullable = false, length = 50)
	private String phone;

	@Column(name = "email", nullable = false, length = 50)
	private String email;

	@Column(name = "enabled", nullable = false)
	private boolean enabled;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false)
	private Date created;

	@Column(name = "status", nullable = false, length = 50)
	private String status;

	@Column(name = "description", length = 500)
	private String description;
	
	@Column(name = "personal_photo_id", length = 500)
	private Long photoId;

	@Column(name = "version", nullable = false)
	private Long version;

	@OneToMany(fetch=FetchType.EAGER,mappedBy = "users", targetEntity = UserRoleEntity.class)
	private List<UserRoleEntity> usersRoles;

	@ManyToOne
	@JoinColumn(name = "user_type_id" , referencedColumnName = "id" ,insertable = false, updatable = false)
	private UserTypeEntity userType;
	
	@Fetch(value = FetchMode.SUBSELECT)
	@OneToMany(fetch=FetchType.EAGER ,mappedBy = "user", targetEntity = UserHubEntity.class)
	private List<UserHubEntity> userHubs;
	
}
