eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    
jsondoc:
  version:
      1.0
  basePath:
      /forgetpassword
  packages[0]:
      com.appzoneltd.lastmile.microservice.forgetpassword.controller
 
      
server:
  port: 0
 
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lastmile
    username: postgres
    password: root
  application:
    name: FORGETPASSWORD
  jpa:
   show-sql: false
   database: default
   hibernate:
     use-new-id-generator-mappings: false
   open-in-view: false

forget_password:
  url: https://localhost:3000/#/resetForgottenPassword/
  from: lastmilesupport@appzone.com

kafka:
  bootstrap:
    servers: localhost:9092  


logging:
  file: forget-password.log