CREATE TABLE lastmile_request.pickup_request
(
  pickup_request_id bigint NOT NULL,
  pickup_request_type_id bigint NOT NULL,
  requesttime timestamp with time zone DEFAULT now(),
  requester_id bigint NOT NULL,
  pickuplongitude character varying(50),
  pickuplatitude character varying(50),
  hub_id bigint,
  pickupwasellocation character varying(200),
  pickupformatedaddress character varying(250),
  time_from character varying(50),
  time_to character varying(50),
  pickupdate date DEFAULT now(),
  recipient_id bigint,
  recipientname character varying(50),
  recipientmobile character varying(20),
  recipientlongitude character varying(50),
  recipientlatitude character varying(50),
  recipientwasellocation character varying(200),
  recipientformatedaddress character varying(250),
  recipientadditionalinfo character varying(250),
  pickup_service_type_id bigint,
  additionalservices character varying(200),
  labelingtext character varying(250),
  paymenttype character varying(100),
  paymentmethod character varying(100),
  description character varying(250),
  version bigint NOT NULL DEFAULT 0,
  created timestamp with time zone DEFAULT now(),
  request_status character varying(50),
  CONSTRAINT pickup_request_pkey PRIMARY KEY (pickup_request_id)
);