/*
 * Created on 20 Jul 2016 ( Time 10:57:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.appzoneltd.lastmile.microservice.pickuptime.dao;

import java.io.Serializable;
import java.util.Date;

/**
 * Java bean for 'VehicleType' entity
 * 
 * @author Telosys Tools
 *
 */
public class PickupTime implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4099444152928786345L;
	private Long pickupTimeId;
	private String fromTime;
	private String toTime;
	private Date created;
	private Long version;

	public PickupTime() {
	}

	public PickupTime(Long pickupTimeId, String fromTime, String toTime, Date created, Long version) {
		super();
		this.pickupTimeId = pickupTimeId;
		this.fromTime = fromTime;
		this.toTime = toTime;
		this.created = created;
		this.version = version;
	}

	public Long getPickupTimeId() {
		return pickupTimeId;
	}

	public void setPickupTimeId(Long pickupTimeId) {
		this.pickupTimeId = pickupTimeId;
	}

	public String getFromTime() {
		return fromTime;
	}

	public void setFromTime(String fromTime) {
		this.fromTime = fromTime;
	}

	public String getToTime() {
		return toTime;
	}

	public void setToTime(String toTime) {
		this.toTime = toTime;
	}

	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

}
