package com.appzoneltd.lastmile.microservices.devices.entity;

/*
 * Created on 23 Oct 2016 ( Time 15:35:11 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

import java.io.Serializable;
import java.util.List;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Persistent class for entity stored in table "device_brand"
 *
 * @author Ahmed.Atef
 *
 */

@Entity
@Table(name = "device_brand",catalog="lastmile", schema="lastmile_core")
public class BrandEntity implements Serializable {

	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------

	private Long brandId;

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	private String brandname;

	// ----------------------------------------------------------------------
	// ENTITY LINKS ( RELATIONSHIP )
	// ----------------------------------------------------------------------
	private List<DeviceEntity> listOfDevice;

	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------
	public void setBrandId(Long brandId) {
		this.brandId = brandId;
	}

	@Id
	@Column(name = "id", nullable = false)
	public Long getBrandId() {
		return this.brandId;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	// --- DATABASE MAPPING : brandname ( varchar )
	public void setBrandname(String brandname) {
		this.brandname = brandname;
	}

	@Column(name = "brandname", nullable = false)
	public String getBrandname() {
		return this.brandname;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR LINKS
	// ----------------------------------------------------------------------
	public void setListOfDevice(List<DeviceEntity> listOfDevice) {
		this.listOfDevice = listOfDevice;
	}

	
	@JsonIgnore
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "deviceBrand", cascade = javax.persistence.CascadeType.PERSIST)
	public List<DeviceEntity> getListOfDevice() {
		return this.listOfDevice;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append("[");
		sb.append(brandId);
		sb.append("]:");
		sb.append(brandname);
		return sb.toString();
	}

}
