eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    
    
jsondoc:
  version: 1.0
  basePath: /countryandcity
  packages[0]: com.appzoneltd.lastmile.microservice.countryandcity.controller
  packages[1]: com.appzoneltd.lastmile.microservice.countryandcity.dao
  
server:
  port: 0
  
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lastmile
    username: postgres
    password: root
  application:
    name: COUNTRYANDCITY
  jpa:
    show-sql: false
    database: default 
    hibernate:
      use-new-id-generator-mappings: false
    open-in-view: false
   
oauth2:
  tokenServiceEndpointUrl: http://localhost:60700/u/oauth/check_token
  clientId: WEB
  clientSecret: WEB   
   
logging:
  file: CountryAndCity.log
  level:
   com.appzoneltd.lastmile.microservice.countryandcity.service: error
   com.appzoneltd.lastmile.microservice.countryandcity.controller: error  
