eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    
server:
  port: 0
  
  
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lastmile
    username: postgres
    password: root
  data:
      cassandra:
        keyspace-name: lastmile
      couchbase:
        auto-index: true
#        contact-points: 192.168.1.105
#        port: 9042
  application:
    name: PICKUPREQUEST
  jpa:
    show-sql: true
    database: default
  couchbase:
    bootstrap-hosts: localhost
    bucket:
      name: vehicle_tracking

oauth2:
  tokenServiceEndpointUrl: http://localhost:60700/u/oauth/check_token
  clientId: WEB
  clientSecret: WEB    
   
kafka:
  bootstrap:
    servers: localhost:9092
   
logging:
  file: PickupRequest.log
  level:
    com.appzoneltd.lastmile.pickuprequest.service: error
    com.appzoneltd.lastmile.pickuprequest.controller: error    
    
jsondoc:
  version: 1.0
  basePath: /pickuprequest
  packages[0]: com.appzoneltd.lastmile.microservice.pickuprequest.controller
  packages[1]: com.appzoneltd.lastmile.microservice.pickuprequest.dao
