/*
 * Created on 19 Oct 2016 ( Time 11:15:01 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.appzoneltd.lastmile.microservice.countryandcity.dao;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * @author alaa.nabil
 *
 */
@Entity
@Table(name = "city", schema = "lastmile_core")
@NamedQueries({ @NamedQuery(name = "CityEntity.countAll", query = "SELECT COUNT(x) FROM CityEntity x") })
public class CityEntity implements Serializable {
	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------
	@Id
	@Column(name = "city_id", nullable = false)
	private Long cityId;

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	@Column(name = "name_ar", nullable = false, length = 50)
	private String nameAr;

	@Column(name = "name_en", nullable = false, length = 50)
	private String nameEn;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false)
	private Date created;

	// "countryId" (column "country_id") is not defined by itself because used
	// as FK in a link

	// ----------------------------------------------------------------------
	// ENTITY LINKS ( RELATIONSHIP )
	// ----------------------------------------------------------------------

	// @ManyToOne
	// @JoinColumn(name = "country_id", referencedColumnName = "country_id")
	// private CountryEntity country;
	@Column(name = "country_id")
	private Long countryId;

	// ----------------------------------------------------------------------
	// CONSTRUCTOR(S)
	// ----------------------------------------------------------------------
	public CityEntity() {
		super();
	}

	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------
	public void setCityId(Long cityId) {
		this.cityId = cityId;
	}

	public Long getCityId() {
		return this.cityId;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	// --- DATABASE MAPPING : name_ar ( varchar )
	public void setNameAr(String nameAr) {
		this.nameAr = nameAr;
	}

	public String getNameAr() {
		return this.nameAr;
	}

	// --- DATABASE MAPPING : name_en ( varchar )
	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	public String getNameEn() {
		return this.nameEn;
	}

	// --- DATABASE MAPPING : created ( timestamptz )
	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getCreated() {
		return this.created;
	}

	public Long getCountryId() {
		return countryId;
	}

	public void setCountryId(Long countryId) {
		this.countryId = countryId;
	}

}
