INSERT INTO module (id, name, version) VALUES (1, 'Package', 0);
INSERT INTO module (id, name, version) VALUES (2, 'Vehicle', 0);
INSERT INTO module (id, name, version) VALUES (3, 'Employee', 0);
INSERT INTO module (id, name, version) VALUES (4, 'Building', 0);
INSERT INTO module (id, name, version) VALUES (5, 'Operation Center', 0);
INSERT INTO module (id, name, version) VALUES (6, 'Vehicle View', 0);
INSERT INTO module (id, name, version) VALUES (7, 'Devices', 0);
INSERT INTO module (id, name, version) VALUES (8, 'Customers' , 0);
INSERT INTO module (id, name, version) VALUES (9, 'Configuration', 0);
INSERT INTO module (id, name, version) VALUES (10, 'Roles Management', 0);
INSERT INTO module (id, name, version) VALUES (11, 'On Demand', 0);
INSERT INTO module (id, name, version) VALUES (12, 'Scheduled', 0);
INSERT INTO module (id, name, version) VALUES (13, 'History', 0);
INSERT INTO module (id, name, version) VALUES (14, 'Active Vehicles', 0);
INSERT INTO module (id, name, version) VALUES (15, 'Calendar', 0);