package com.appzoneltd.lastmile.microservice.pickuprequest.dto;

/**
 * Created by hashish on 5/22/2017.
 */
public enum PackageStatus {
    NEW , WAITING_FOR_CUSTOMER_ALTERNATIVE , SCHEDULED_FOR_PICKUP , AWAITING_PICKUP , IN_PICKUP_VERIFICATION ,
    PICKEDUP , CANCELED , SCHEDULED_FOR_DELIVERY , OUT_FOR_DELIVERY , DELIVERED , IN_DELIVERY_VERIFICATION, CANCELED_DELIVERY , ACTION_NEEDED,
    RESCHEDULED_FOR_DELIVERY , SCHEDULED_FOR_RETURN , RESCHEDULED_FOR_RETURN , OUT_FOR_RETURN , RETURNED
}
