/*
 * Created on 28 Mar 2017 ( Time 13:35:12 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.appzoneltd.lastmile.microservice.returnworkflow.business.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;


@Entity
@Table(name = "calendar", schema = "lastmile_core")
@NamedQueries({ @NamedQuery(name = "CalendarEntity.countAll", query = "SELECT COUNT(x) FROM CalendarEntity x") })
public class CalendarEntity implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "id", nullable = false)
	private Long id;

	@Column(name = "dayname", nullable = false, length = 50)
	private String dayname;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false)
	private Date created;

	@Column(name = "version", nullable = false)
	private Long version;

	@Column(name = "status", length = 50)
	private String status;

	public CalendarEntity() {
		super();
	}
	
	public void setId(Long id) {
		this.id = id;
	}

	public Long getId() {
		return this.id;
	}

	public void setDayname(String dayname) {
		this.dayname = dayname;
	}

	public String getDayname() {
		return this.dayname;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public Long getVersion() {
		return this.version;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getStatus() {
		return this.status;
	}

	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append("[");
		sb.append(id);
		sb.append("]:");
		sb.append(dayname);
		sb.append("|");
		sb.append(created);
		sb.append("|");
		sb.append(version);
		sb.append("|");
		sb.append(status);
		return sb.toString();
	}

}
