/*
 * Created on 20 Nov 2016 ( Time 10:25:47 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.appzoneltd.lastmile.microservice.returnworkflow.business.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * @author alaa.nabil
 *
 */
@Entity
@Table(name = "devices", schema = "lastmile_core")
@NamedQueries({ @NamedQuery(name = "DevicesEntity.countAll", query = "SELECT COUNT(x) FROM DevicesEntity x") })
public class DevicesEntity implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "device_id", nullable = false)
	private Long deviceId;

	@Column(name = "model", nullable = false, length = 500)
	private String model;

	@Column(name = "imei_info", nullable = false, length = 500)
	private String imeiInfo;

	@Column(name = "phonenumber", nullable = false, length = 500)
	private String phonenumber;

	@Column(name = "status", length = 2147483647)
	private String status;

	@Column(name = "version", nullable = false)
	private Long version;

	@Temporal(TemporalType.TIME)
	@Column(name = "created")
	private Date created;

	public DevicesEntity() {
		super();
	}

	public void setDeviceId(Long deviceId) {
		this.deviceId = deviceId;
	}

	public Long getDeviceId() {
		return this.deviceId;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getModel() {
		return this.model;
	}

	public void setImeiInfo(String imeiInfo) {
		this.imeiInfo = imeiInfo;
	}

	public String getImeiInfo() {
		return this.imeiInfo;
	}

	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

	public String getPhonenumber() {
		return this.phonenumber;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getStatus() {
		return this.status;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public Long getVersion() {
		return this.version;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getCreated() {
		return this.created;
	}

}
