/*
 * Created on 25 Apr 2017 ( Time 12:56:09 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.appzoneltd.lastmile.microservice.freelancedriver.model;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "country_codes"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="country_codes", schema="lastmile_core" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="CountryCodesEntity.countAll", query="SELECT COUNT(x) FROM CountryCodesEntity x" )
} )
public class CountryCodesEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="id", nullable=false)
    private Long       id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="iso", nullable=false, length=2147483647)
    private String     iso          ;

    @Column(name="name", nullable=false, length=80)
    private String     name         ;

    @Column(name="nicename", nullable=false, length=80)
    private String     nicename     ;

    @Column(name="iso3", length=2147483647)
    private String     iso3         ;

    @Column(name="numcode")
    private Long       numcode      ;

    @Column(name="phonecode", nullable=false)
    private Long       phonecode    ;



  


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public CountryCodesEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : iso ( varchar ) 
    public void setIso( String iso ) {
        this.iso = iso;
    }
    public String getIso() {
        return this.iso;
    }

    //--- DATABASE MAPPING : name ( varchar ) 
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    //--- DATABASE MAPPING : nicename ( varchar ) 
    public void setNicename( String nicename ) {
        this.nicename = nicename;
    }
    public String getNicename() {
        return this.nicename;
    }

    //--- DATABASE MAPPING : iso3 ( varchar ) 
    public void setIso3( String iso3 ) {
        this.iso3 = iso3;
    }
    public String getIso3() {
        return this.iso3;
    }

    //--- DATABASE MAPPING : numcode ( int8 ) 
    public void setNumcode( Long numcode ) {
        this.numcode = numcode;
    }
    public Long getNumcode() {
        return this.numcode;
    }

    //--- DATABASE MAPPING : phonecode ( int8 ) 
    public void setPhonecode( Long phonecode ) {
        this.phonecode = phonecode;
    }
    public Long getPhonecode() {
        return this.phonecode;
    }




    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(iso);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(nicename);
        sb.append("|");
        sb.append(iso3);
        sb.append("|");
        sb.append(numcode);
        sb.append("|");
        sb.append(phonecode);
        return sb.toString(); 
    } 

}
