/*
 * Created on 7 Aug 2016 ( Time 14:48:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.appzoneltd.lastmile.microservice.drivinglicensetype.dao;

import java.io.Serializable;
import java.util.Date;

/**
 * @author alaa.nabil
 *
 */
public class DrivingLicenseType implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3653553503891783605L;
	private Long drivingLicenseTypeId;
	private String licenseType;
	private Date created;
	private Long version;

	public DrivingLicenseType() {
	}

	public DrivingLicenseType(Long drivingLicenseTypeId, String licenseType, Date created, Long version) {
		super();
		this.drivingLicenseTypeId = drivingLicenseTypeId;
		this.licenseType = licenseType;
		this.created = created;
		this.version = version;
	}

	public Long getDrivingLicenseTypeId() {
		return drivingLicenseTypeId;
	}

	public void setDrivingLicenseTypeId(Long drivingLicenseTypeId) {
		this.drivingLicenseTypeId = drivingLicenseTypeId;
	}

	public String getLicenseType() {
		return licenseType;
	}

	public void setLicenseType(String licenseType) {
		this.licenseType = licenseType;
	}

	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}
}
