/*
 * Created on 6 Aug 2017 ( Time 15:18:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.appzoneltd.lastmile.microservices.stats.lastmile.entity;

import javax.persistence.*;
import java.io.Serializable;

@Entity
@Table(name = "country", schema = "lastmile_core")
// Define named queries here
@NamedQueries({
        @NamedQuery(name = "CountryEntity.countAll", query = "SELECT COUNT(x) FROM CountryEntity x")
})
public class CountryEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @Column(name = "country_id", nullable = false)
    private Long countryId;

    @Column(name = "name_ar", nullable = false, length = 50)
    private String nameAr;

    @Column(name = "name_en", nullable = false, length = 50)
    private String nameEn;

    public CountryEntity() {
        super();
    }

    public Long getCountryId() {
        return this.countryId;
    }

    public void setCountryId(Long countryId) {
        this.countryId = countryId;
    }

    public String getNameAr() {
        return this.nameAr;
    }

    public void setNameAr(String nameAr) {
        this.nameAr = nameAr;
    }

    public String getNameEn() {
        return this.nameEn;
    }

    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }
}
