kafka:
  bootstrap:
    servers: 192.168.88.90:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.88.90:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 0

spring:
  application:
     name: DELIVERY
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.88.90:5432/lastmile
    username: postgres
    password: root
  jpa:
    show-sql: false
#    hibernate:
#      ddl-auto: none
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

oauth2:
  tokenServiceEndpointUrl: http://192.168.88.90:60700/u/oauth/check_token
  clientId: WEB
  clientSecret: WEB
