eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

    
jsondoc:
  version:
      1.0
  basePath:
      /packagelabel
  packages[0]:
      com.appzoneltd.lastmile.microservice.packagelabel.controller
  packages[1]:
      com.appzoneltd.lastmile.microservice.packagelabel.dao
      
server:
  port: 0
 
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lastmile
    username: postgres
    password: root
  application:
    name: PACKAGELABEL
   
oauth2:
  tokenServiceEndpointUrl: http://localhost:60700/u/oauth/check_token
  clientId: WEB
  clientSecret: WEB    
   
logging:
  file: PackageLabel.log
  level:
    com.appzoneltd.lastmile.microservice.packagelabel.service: error
    com.appzoneltd.lastmile.microservice.packagelabel.controller: error