/*
 * Created on 7 Nov 2016 ( Time 13:02:27 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.appzoneltd.lastmile.microservice.pickuprequest.dao.requesthistory;

public interface RequestHistoryRepository {

	String SQL_SELECT = "SELECT request_history_id, package_id, request_status, created, request_id, request_type, version FROM lastmile_request.request_history WHERE request_history_id = ?";
	
	String SQL_SELECT_ALL = "SELECT request_history_id, package_id, request_status, created, request_id, request_type, version FROM lastmile_request.request_history";

	String SQL_INSERT = "INSERT INTO lastmile_request.request_history ( request_history_id, package_id, request_status, request_id ,request_type ) values ( ?, ?, ?, ? , ? )";

	String SQL_UPDATE = "UPDATE lastmile_request.request_history SET package_id = ?, request_status = ?, request_id = ?, request_type = ? , version = version+1 WHERE request_history_id = ?";

	String SQL_DELETE = "DELETE FROM lastmile_request.request_history WHERE request_history_id = ?";

	String SQL_COUNT_ALL = "SELECT COUNT(*) FROM lastmile_request.request_history";
	
	String SQL_SELECT_REQUEST_STATUS="SELECT request_status, created FROM lastmile_request.request_history WHERE request_status!='' AND request_type='PICKUP' AND request_id= ? ORDER BY created ASC ";
	
String SQL_SELECT_REQUEST_ID="SELECT DISTINCT request_id FROM lastmile_request.request_history WHERE package_id = ?";
	

}
