eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

#security:
#  basic:
#    enabled: false
#  oauth2:
#    resource:
#      userInfoUri: http://localhost:8080/u/user
    
jsondoc:
  version:
      1.0
  basePath:
      /vehicletype
  packages[0]:
      com.appzoneltd.lastmile.microservice.vehicletype.controller
  packages[1]:
      com.appzoneltd.lastmile.microservice.vehicletype.dao
      
server:
  port: 0

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lastmile
    username: postgres
    password: root
  application:
    name: VEHICLETYPE

oauth2:
  tokenServiceEndpointUrl: http://localhost:60700/u/oauth/check_token
  clientId: WEB
  clientSecret: WEB 
   
logging:
  file: VehicleType.log
  level:
    com.appzoneltd.lastmile.microservice.vehicletype.service: error
    com.appzoneltd.lastmile.microservice.vehicletype.controller: error    
    
security:
  ignored: /findall  
   