/*
 * Created on 25 Sep 2017 ( Time 15:18:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.appzoneltd.lastmile.microservice.ondemandworkflow.business.entity;

import java.io.Serializable;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.persistence.*;

import lombok.Data;

@Data
@Entity
@Table(name = "driver", schema = "lastmile_core")
public class DriverEntity implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "id", nullable = false)
	private Long id;

	@Column(name = "national_id", length = 50)
	private String nationalId;

	@Temporal(TemporalType.DATE)
	@Column(name = "driving_license_exp_date")
	private Date drivingLicenseExpDate;

	@Column(name = "driving_license_id", length = 50)
	private String drivingLicenseId;

	@Column(name = "rating")
	private BigDecimal rating;

	@OneToMany(mappedBy = "driver", targetEntity = ActiveVehicleEntity.class)
	private List<ActiveVehicleEntity> listOfActiveVehicle;
}
