/*
 * Created on 28 Dec 2016 ( Time 17:43:57 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.appzoneltd.lastmile.microservice.ondemandworkflow.business.entity;

import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;

@Data
@Entity
@Table(name = "request_cancellation", schema = "lastmile_request")
public class RequestCancelationEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @Column(name = "request_id", nullable = false)
    private Long requestId;

    @Column(name = "reason_id", nullable = false, length = 200)
    private Long reasonId;

    @Column(name = "description")
    private String description;

}
