/*
 * Created on 27 Dec 2016 ( Time 16:30:50 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.appzoneltd.lastmile.microservice.details.dao.entity;

import java.io.Serializable;

import javax.persistence.*;

@Embeddable
public class PackageLabelingEntityKey implements Serializable {

	private static final long serialVersionUID = 1L;

	@Column(name = "package_id", nullable = false)
	private Long packageId;

	@Column(name = "package_label_id", nullable = false)
	private Long packageLabelId;

	public PackageLabelingEntityKey() {
		super();
	}

	public PackageLabelingEntityKey(Long packageId, Long packageLabelId) {
		super();
		this.packageId = packageId;
		this.packageLabelId = packageLabelId;
	}

	public void setPackageId(Long value) {
		this.packageId = value;
	}

	public Long getPackageId() {
		return this.packageId;
	}

	public void setPackageLabelId(Long value) {
		this.packageLabelId = value;
	}

	public Long getPackageLabelId() {
		return this.packageLabelId;
	}

}
