/*
 * Created on 27 Dec 2016 ( Time 16:30:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.appzoneltd.lastmile.microservice.details.dao.entity;

import java.io.Serializable;

import javax.persistence.*;

@Embeddable
public class PackageImagesEntityKey implements Serializable {

	private static final long serialVersionUID = 1L;

	@Column(name = "package_id", nullable = false)
	private Long packageId;

	@Column(name = "image_id", nullable = false)
	private Long imageId;

	public PackageImagesEntityKey() {
		super();
	}

	public PackageImagesEntityKey(Long packageId, Long imageId) {
		super();
		this.packageId = packageId;
		this.imageId = imageId;
	}

	public void setPackageId(Long value) {
		this.packageId = value;
	}

	public Long getPackageId() {
		return this.packageId;
	}

	public void setImageId(Long value) {
		this.imageId = value;
	}

	public Long getImageId() {
		return this.imageId;
	}

}
