/*
 * Created on 16 Nov 2016 ( Time 12:31:50 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.appzoneltd.lastmile.microservices.SizesConfiguration.model;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.*;



/**
 * Persistent class for entity stored in table "sizes_config"
 *
 * @author ahmed.atef
 *
 */

@Entity
@Table(name = "sizes_config", schema = "lastmile_core")
public class SizesConfig implements Serializable {

	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------
	@Id
	@Column(name = "size_id", nullable = false)
	private Long sizeId;

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	@Column(name = "sizename")
	private String sizeName;

	@Column(name = "width")
	private BigDecimal width;

	@Column(name = "height")
	private BigDecimal height;

	@Column(name = "length")
	private BigDecimal length;

	@Column(name = "correspondence")
	private BigDecimal correspondence;
	
	@Version
	private Long version ;
	
	private String status ;
	
	
	private Date created = new Date();

	
	public SizesConfig() {
		
	}

	
	public void setSizeId(Long sizeId) {
		this.sizeId = sizeId;
	}

	public Long getSizeId() {
		return this.sizeId;
	}

	

	public String getSizeName() {
		return sizeName;
	}

	public void setSizeName(String sizeName) {
		this.sizeName = sizeName;
	}

	
	public void setWidth(BigDecimal width) {
		this.width = width;
	}

	public BigDecimal getWidth() {
		return this.width;
	}

	
	public void setHeight(BigDecimal height) {
		this.height = height;
	}

	public BigDecimal getLength() {
		return length;
	}

	public void setLength(BigDecimal length) {
		this.length = length;
	}

	public BigDecimal getHeight() {
		return this.height;
	}


	public void setCorrespondence(BigDecimal correspondence) {
		this.correspondence = correspondence;
	}

	public BigDecimal getCorrespondence() {
		return this.correspondence;
	}


	@Temporal(value=TemporalType.TIMESTAMP)
	@Column(name = "created" , insertable = false, updatable = false )
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}
	
	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public String getStatus() {
		return status;
	}

	@Column(name = "status" )
	public void setStatus(String status) {
		this.status = status;
	}


	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append("[");
		sb.append(sizeId);
		sb.append("]:");
		sb.append(sizeName);
		sb.append("|");
		sb.append(width);
		sb.append("|");
		sb.append(height);
		sb.append("|");
		sb.append(length);
		sb.append("|");
		sb.append(correspondence);
		sb.append("|");
		sb.append(status);
		
		return sb.toString();
	}

}
