eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    
jsondoc:
  version:
      1.0
  basePath:
      /scheduledrequest
  packages[0]:
      com.appzoneltd.lastmile.microservice.scheduledrequest.service
  packages[1]:
      com.appzoneltd.lastmile.microservice.scheduledrequest.model  
  packages[2]:
      com.appzoneltd.lastmile.microservice.scheduledrequest.json                

      
