/*
 * Created on 6 Aug 2017 ( Time 15:18:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.appzoneltd.lastmile.microservice.delivery.dao.entity;

import javax.persistence.*;
import java.io.Serializable;

@Entity
@Table(name = "pickup_request_type", schema = "lastmile_request")
@NamedQueries({
        @NamedQuery(name = "PickupRequestTypeEntity.countAll", query = "SELECT COUNT(x) FROM PickupRequestTypeEntity x")
})
public class PickupRequestTypeEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @Column(name = "pickup_request_type_id", nullable = false)
    private Long pickupRequestTypeId;

    @Column(name = "type", nullable = false, length = 50)
    private String type;

    public PickupRequestTypeEntity() {
        super();
    }

    public Long getPickupRequestTypeId() {
        return this.pickupRequestTypeId;
    }

    public void setPickupRequestTypeId(Long pickupRequestTypeId) {
        this.pickupRequestTypeId = pickupRequestTypeId;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
