/*
 * Created on 20 Nov 2016 ( Time 16:29:30 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.appzoneltd.lastmile.microservice.activevehicle.dao;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "driver"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name = "driver", schema = "lastmile_core")
@NamedQueries({ @NamedQuery(name = "DriverEntity.countAll", query = "SELECT COUNT(x) FROM DriverEntity x") })
public class DriverEntity implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7446937162380829976L;

	@Id
	@Column(name = "id", nullable = false)
	private Long id;

	@ManyToOne
	@JoinColumn(name = "id", referencedColumnName = "user_id", insertable = false, updatable = false)
	private UsersEntity users;

	@Column(name = "rating")
	private BigDecimal rating;

	public DriverEntity() {
		super();
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getId() {
		return this.id;
	}

	public void setUsers(UsersEntity users) {
		this.users = users;
	}

	public UsersEntity getUsers() {
		return this.users;
	}

	public BigDecimal getRating() {
		return rating;
	}

	public void setRating(BigDecimal rating) {
		this.rating = rating;
	}

}
