/*
 * Created on 22 Nov 2016 ( Time 11:46:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.appzoneltd.lastmile.microservice.activevehicle.dao;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * @author alaa.nabil
 *
 */
@Entity
@Table(name = "vehicle", schema = "lastmile_core")
@NamedQueries({ @NamedQuery(name = "VehicleEntity.countAll", query = "SELECT COUNT(x) FROM VehicleEntity x") })
public class VehicleEntity implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "vehicle_id", nullable = false)
	private Long vehicleId;

	@Column(name = "brand", nullable = false, length = 50)
	private String brand;

	@Column(name = "model", nullable = false, length = 50)
	private String model;

	@Column(name = "color", length = 50)
	private String color;

	@Column(name = "plate", nullable = false, length = 50)
	private String plate;

	@Column(name = "chassis", nullable = false, length = 100)
	private String chassis;

	@Column(name = "weight", nullable = false)
	private BigDecimal weight;

	@Column(name = "purpose", length = 50)
	private String purpose;

	@Column(name = "motor", length = 50)
	private String motor;

	@Column(name = "status", nullable = false, length = 50)
	private String status;

	@Column(name = "description", length = 500)
	private String description;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false)
	private Date created;

	@Column(name = "version", nullable = false)
	private Long version;

	@Column(name = "building_id")
	private Long buildingId;

	@ManyToOne
	@JoinColumn(name = "vehicle_type_id", referencedColumnName = "vehicle_type_id")
	private VehicleTypeEntity vehicleType;

	public VehicleEntity() {
		super();
	}

	public void setVehicleId(Long vehicleId) {
		this.vehicleId = vehicleId;
	}

	public Long getVehicleId() {
		return this.vehicleId;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getBrand() {
		return this.brand;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getModel() {
		return this.model;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public String getColor() {
		return this.color;
	}

	public void setPlate(String plate) {
		this.plate = plate;
	}

	public String getPlate() {
		return this.plate;
	}

	public void setChassis(String chassis) {
		this.chassis = chassis;
	}

	public String getChassis() {
		return this.chassis;
	}

	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	public BigDecimal getWeight() {
		return this.weight;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	public String getPurpose() {
		return this.purpose;
	}

	public void setMotor(String motor) {
		this.motor = motor;
	}

	public String getMotor() {
		return this.motor;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getStatus() {
		return this.status;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDescription() {
		return this.description;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public Long getVersion() {
		return this.version;
	}

	public Long getBuildingId() {
		return buildingId;
	}

	public void setBuildingId(Long buildingId) {
		this.buildingId = buildingId;
	}

	public void setVehicleType(VehicleTypeEntity vehicleType) {
		this.vehicleType = vehicleType;
	}

	public VehicleTypeEntity getVehicleType() {
		return this.vehicleType;
	}

}
