/*
 * Created on 23 Nov 2016 ( Time 14:06:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.appzoneltd.lastmile.microservice.activevehicle.dao;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "vehicle_type"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name = "vehicle_type", schema = "lastmile_core")
@NamedQueries({ @NamedQuery(name = "VehicleTypeEntity.countAll", query = "SELECT COUNT(x) FROM VehicleTypeEntity x") })
public class VehicleTypeEntity implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "vehicle_type_id", nullable = false)
	private Long vehicleTypeId;

	@Column(name = "type", nullable = false, length = 50)
	private String type;

	public VehicleTypeEntity() {
		super();
	}

	public void setVehicleTypeId(Long vehicleTypeId) {
		this.vehicleTypeId = vehicleTypeId;
	}

	public Long getVehicleTypeId() {
		return this.vehicleTypeId;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getType() {
		return this.type;
	}

}
