/*
 * Created on 20 Jul 2016 ( Time 10:57:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.appzoneltd.lastmile.microservice.packagelabel.dao;

import java.io.Serializable;
import java.util.Date;

/**
 * Java bean for 'PackageLabel' entity
 * 
 * @author Telosys Tools
 *
 */
public class PackageLabel implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1461166529269550336L;
	private Long packageLabelId;
	private String label;
	private Date created;
	private Long version;

	public PackageLabel() {
	}

	public PackageLabel(Long packageLabelId, String label, Date created, Long version) {
		super();
		this.packageLabelId = packageLabelId;
		this.label = label;
		this.created = created;
		this.version = version;
	}

	public Long getPackageLabelId() {
		return packageLabelId;
	}

	public void setPackageLabelId(Long packageLabelId) {
		this.packageLabelId = packageLabelId;
	}

	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

}
