/*
 * Created on 20 Jul 2016 ( Time 10:57:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.appzoneltd.lastmile.microservice.buildingtype.dao;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Java bean for 'VehicleType' entity
 * 
 *
 */
@Entity
@Table(name = "building_type", schema = "lastmile_core")
public class BuildingTypeEntity implements Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@Column(name = "building_type_id")
	private Long buildingTypeId;
	@Column(name = "type")
	private String type;
	@Column(name = "created")
	private Date created;
	@Column(name = "version")
	@Version
	private Long version;

	public BuildingTypeEntity() {

	}

	public BuildingTypeEntity(Long buildingTypeId, String type, Date created, Long version) {

		this.buildingTypeId = buildingTypeId;
		this.type = type;
		this.created = created;
		this.version = version;
	}

	public void setBuildingTypeId(Long buildingTypeId) {
		this.buildingTypeId = buildingTypeId;
	}

	public Long getBuildingTypeId() {
		return this.buildingTypeId;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getType() {
		return this.type;
	}

	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

}
