/*
 * Created on 4 May 2016 ( Time 11:29:27 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.appzoneltd.lastmile.microservice.vehicle.dao;

import com.appzoneltd.lastmile.microservice.enums.EntityStatus;
import org.hibernate.validator.constraints.NotEmpty;

import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Java bean for 'Vehicle' entity
 *
 * @author Alaa Nabil
 */
public class Vehicle implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = -7305305472640313343L;


    private Long vehicleId;

    @NotNull(message = "vehicle.vehicletypeid.notnull")
    private Long vehicleTypeId;

    @NotEmpty(message = "vehicle.brand.notempty")
    @Pattern(regexp = "^$|^[a-zA-Z0-9\u0621-\u064A\u0660-\u0669][a-zA-Z0-9\u0621-\u064A\u0660-\u0669 ]*", message = "vehicle.brand.regex")
    private String brand;

    @NotEmpty(message = "vehicle.model.notempty")
    @Pattern(regexp = "^$|^[a-zA-Z0-9\u0621-\u064A\u0660-\u0669][a-zA-Z0-9\u0621-\u064A\u0660-\u0669 ]*", message = "vehicle.model.regex")
    private String model;

    @NotEmpty(message = "vehicle.color.notempty")
    @Pattern(regexp = "^$|^[a-zA-Z\u0621-\u064A\u0660-\u0669][a-zA-Z\u0621-\u064A\u0660-\u0669 ]*", message = "vehicle.color.regex")
    private String color;

    @NotEmpty(message = "vehicle.plate.notempty")
    @Pattern(regexp = "^$|^[a-zA-Z0-9\u0621-\u064A\u0660-\u0669][a-zA-Z0-9\u0621-\u064A\u0660-\u0669 -]*[a-zA-Z0-9\u0621-\u064A\u0660-\u0669]+]*", message = "vehicle.plate.regex")
    private String plate;

    @NotEmpty(message = "vehicle.chassis.notempty")
    @Pattern(regexp = "^$|^[a-zA-Z0-9\u0621-\u064A\u0660-\u0669][a-zA-Z0-9\u0621-\u064A\u0660-\u0669 ]*", message = "vehicle.chassis.regex")
    private String chassis;

    @NotNull(message = "vehicle.weight.notnull")
    @Digits(integer = 19, fraction = 2, message = "vehicle.weight.valid")
    private BigDecimal weight;

    @NotNull(message = "vehicle.purpose.notempty")
//	@Pattern(regexp = "^$|^[a-zA-Z0-9\u0621-\u064A\u0660-\u0669][a-zA-Z0-9\u0621-\u064A\u0660-\u0669 ]*", message = "vehicle.purpose.regex")
    private Purpose purpose;

    @NotNull(message = "vehicle.motor.notnull")
    @Pattern(regexp = "^$|^[a-zA-Z0-9][a-zA-Z0-9 -]*[a-zA-Z0-9]+", message = "vehicle.motor.regex")
    private String motor;

    private Long buildingId;

    @Size(max = 500, message = "vehicle.description.size")
    private String description;

    private EntityStatus status;

    private Date created;

    private Long version;

    public Vehicle() {

    }

    public Vehicle(Long vehicleId, Long vehicleTypeId, String brand, String model, String color, String plate,
                   String chassis, BigDecimal weight, Purpose purpose, String motor, Long buildingId, String description,
                   EntityStatus status, Date created, Long version) {
        super();
        this.vehicleId = vehicleId;
        this.vehicleTypeId = vehicleTypeId;
        this.brand = brand;
        this.model = model;
        this.color = color;
        this.plate = plate;
        this.chassis = chassis;
        this.weight = weight;
        this.purpose = purpose;
        this.motor = motor;
        this.buildingId = buildingId;
        this.description = description;
        this.status = status;
        this.created = created;
        this.version = version;
    }

    public Long getVehicleId() {
        return vehicleId;
    }

    public void setVehicleId(Long vehicleId) {
        this.vehicleId = vehicleId;
    }

    public Long getVehicleTypeId() {
        return vehicleTypeId;
    }

    public void setVehicleTypeId(Long vehicleTypeId) {
        this.vehicleTypeId = vehicleTypeId;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getPlate() {
        return plate;
    }

    public void setPlate(String plate) {
        this.plate = plate;
    }

    public String getChassis() {
        return chassis;
    }

    public void setChassis(String chassis) {
        this.chassis = chassis;
    }

    public BigDecimal getWeight() {
        return weight;
    }

    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    public Purpose getPurpose() {
        return purpose;
    }

    public void setPurpose(Purpose purpose) {
        this.purpose = purpose;
    }

    public String getMotor() {
        return motor;
    }

    public void setMotor(String motor) {
        this.motor = motor;
    }

    public Long getBuildingId() {
        return buildingId;
    }

    public void setBuildingId(Long buildingId) {
        this.buildingId = buildingId;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public EntityStatus getStatus() {
        return status;
    }

    public void setStatus(EntityStatus status) {
        this.status = status;
    }

    public Date getCreated() {
        return created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

}
