/*
 * Created on 31 May 2016 ( Time 16:04:02 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.appzoneltd.lastmile.microservice.SystemConfig.dao;

import com.appzoneltd.lastmile.microservice.enums.EntityStatus;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Java bean for 'SystemConfig' entity
 *
 * @author Telosys Tools
 */
public class SystemConfig implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 8650442468712226435L;

    private Long configId;
    private BigDecimal value;
    private String textValue;
    private String displayname;
    private String description;
    private String unit;
    private EntityStatus status;
    private Long version;
    private Date created;


    public SystemConfig() {
    }

    public SystemConfig(Long configId, BigDecimal value, String displayname, String description, String unit,
                        EntityStatus status, Long version, Date created) {
        super();
        this.configId = configId;
        this.value = value;
        this.displayname = displayname;
        this.description = description;
        this.unit = unit;
        this.status = status;
        this.version = version;
        this.created = created;
    }

    public String getTextValue() {
        return textValue;
    }

    public void setTextValue(String textValue) {
        this.textValue = textValue;
    }

    public Long getConfigId() {
        return configId;
    }

    public void setConfigId(Long configId) {
        this.configId = configId;
    }

    public BigDecimal getValue() {
        return value;
    }

    public void setValue(BigDecimal value) {
        this.value = value;
    }

    public String getDisplayname() {
        return displayname;
    }

    public void setDisplayname(String displayname) {
        this.displayname = displayname;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public EntityStatus getStatus() {
        return status;
    }

    public void setStatus(EntityStatus status) {
        this.status = status;
    }

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public Date getCreated() {
        return created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @Override
    public String toString() {
        return "SystemConfig{" +
                "configId=" + configId +
                ", value=" + value +
                ", textValue='" + textValue + '\'' +
                ", displayname='" + displayname + '\'' +
                ", description='" + description + '\'' +
                ", unit='" + unit + '\'' +
                ", status=" + status +
                ", version=" + version +
                ", created=" + created +
                '}';
    }
}
