/*
 * Created on 1 Nov 2016 ( Time 11:42:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.appzoneltd.lastmile.microservice.shipmentservice.dao;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

@Entity
@Table(name = "shipment_service", schema = "lastmile_core")
@NamedQueries({
		@NamedQuery(name = "ShipmentServiceEntity.countAll", query = "SELECT COUNT(x) FROM ShipmentServiceEntity x") })
public class ShipmentServiceEntity implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8302546482875243393L;

	@Id
	@Column(name = "shipment_service_id", nullable = false)
	private Long shipmentServiceId;

	@Column(name = "service", nullable = false, length = 50)
	private String service;

	@Column(name = "description", length = 500)
	private String description;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false)
	private Date created;

	@Column(name = "version", nullable = false)
	@Version
	private Long version;

	public ShipmentServiceEntity() {
		super();
	}

	public void setShipmentServiceId(Long shipmentServiceId) {
		this.shipmentServiceId = shipmentServiceId;
	}

	public Long getShipmentServiceId() {
		return this.shipmentServiceId;
	}

	public void setService(String service) {
		this.service = service;
	}

	public String getService() {
		return this.service;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDescription() {
		return this.description;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public Long getVersion() {
		return this.version;
	}

}
