/*
 * Created on 1 Nov 2016 ( Time 11:43:01 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.appzoneltd.lastmile.microservice.shipmentservice.dao;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

@Entity
@Table(name = "shipment_service_type", schema = "lastmile_core")
@NamedQueries({
		@NamedQuery(name = "ShipmentServiceTypeEntity.countAll", query = "SELECT COUNT(x) FROM ShipmentServiceTypeEntity x") })
public class ShipmentServiceTypeEntity implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4669319724785597532L;

	@Id
	@Column(name = "shipment_service_type_id", nullable = false)
	private Long shipmentServiceTypeId;

	@Column(name = "type", nullable = false, length = 50)
	private String type;

	@Column(name = "description", length = 500)
	private String description;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false)
	private Date created;

	@Column(name = "version", nullable = false)
	@Version
	private Long version;

	// @ManyToOne
	// @JoinColumn(name = "shipment_service_id", referencedColumnName =
	// "shipment_service_id")
	@Column(name = "shipment_service_id")
	private Long shipmentServiceId;

	public ShipmentServiceTypeEntity() {
		super();
	}

	public void setShipmentServiceTypeId(Long shipmentServiceTypeId) {
		this.shipmentServiceTypeId = shipmentServiceTypeId;
	}

	public Long getShipmentServiceTypeId() {
		return this.shipmentServiceTypeId;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getType() {
		return this.type;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDescription() {
		return this.description;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public Long getVersion() {
		return this.version;
	}

	public Long getShipmentServiceId() {
		return shipmentServiceId;
	}

	public void setShipmentServiceId(Long shipmentServiceId) {
		this.shipmentServiceId = shipmentServiceId;
	}

}
