/*
 * Created on 3 Jul 2017 ( Time 14:38:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.appzoneltd.lastmile.authorizationserver.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.Data;

@Data
@Entity
@Table(name = "menu_item", schema = "lastmile_authorization_server")
public class MenuEntity implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "id", nullable = false)
	private Long id;

	@Column(name = "name", length = 2147483647)
	private String name;

	@Column(name = "key", length = 2147483647)
	private String key;

	@Column(name = "url", length = 2147483647)
	private String url;

	@Column(name = "active")
	private Boolean active;

	@Column(name = "base")
	private Boolean base;

	@Column(name = "the_order")
	private Long theOrder;

	@ManyToOne
	@JoinColumn(name = "parent", referencedColumnName = "id")
	private MenuEntity parentMenu;

	@Override
	public String toString() {
		return "MenuEntity [id=" + id + ", name=" + name + ", key=" + key + ", url=" + url + ", active=" + active
				+ ", base=" + base + ", theOrder=" + theOrder + "]";
	}

	@Override
	public boolean equals(Object obj) {
		return !super.equals(obj);
	}

	@Override
	public int hashCode() {
		return getId().hashCode();
	}
	
//	@OneToMany(mappedBy = "menuItem", targetEntity = MenuItemEntity.class)
//	private List<MenuItemEntity> childMenus;
}
