/*
 * Created on 3 Jul 2017 ( Time 14:38:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.appzoneltd.lastmile.authorizationserver.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.Data;

/**
 * Persistent class for entity stored in table "roles"
 *
 * @author Telosys Tools Generator
 *
 */

@Data
@Entity
@Table(name = "roles", schema = "lastmile_authorization_server")
public class RoleEntity implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "role_id", nullable = false)
	private Long roleId;

	@Column(name = "rolename", nullable = false, length = 100)
	private String rolename;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false)
	private Date created;

	@Column(name = "editable", nullable = false)
	private boolean editable=false;

	@Column(name = "description", length = 500)
	private String description;

	@Column(name = "version", nullable = false)
	private Long version;

	@Column(name = "enabled")
	private boolean enabled=true;

	@OneToMany(fetch = FetchType.EAGER,mappedBy = "roles", targetEntity = RolePrivilegeEntity.class)
	private List<RolePrivilegeEntity> rolePrivileges;

	@ManyToOne
	@JoinColumn(name = "hub_id", referencedColumnName = "building_id")
	private BuildingEntity building;
	
}
