/*
 * Created on 3 Jul 2017 ( Time 14:38:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.appzoneltd.lastmile.authorizationserver.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.Data;

@Data
@Entity
@Table(name = "system_role_privilege", schema = "lastmile_authorization_server")
public class SystemRolePrivilegeEntity implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "id", nullable = false)
	private Long id;

	@ManyToOne
	@JoinColumn(name = "system_role_id", referencedColumnName = "id")
	private SystemRoleEntity systemRole;

	@ManyToOne
	@JoinColumn(name = "module_privilege_id", referencedColumnName = "id")
	private ModulePrivilegeEntity modulePrivilege;

}
