server:
  port: 0
  
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lastmile
    username: postgres
    password: root
  application:
    name: WORKFLOWSERVICE
  couchbase:
    bootstrap-hosts: localhost
    bucket:
      name: vehicle_tracking
  data:
    couchbase:
      auto-index: true
  jpa:
      show-sql: true
      database: default
      hibernate:
        use-new-id-generator-mappings: false
      open-in-view: false

  
kafka:
  bootstrap:
    servers: localhost:9092       
  
logging:
  file: WorkFlowService22.log
