/*
 * Created on 20 Jul 2016 ( Time 10:57:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.appzoneltd.lastmile.microservice.vehicletype.dao;

import java.io.Serializable;
import java.util.Date;

/**
 * @author alaa.nabil
 *
 */
public class VehicleType implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -624781514825879103L;
	private Long vehicleTypeId;
	private String type;
	private Date created;
	private Long version;

	public VehicleType() {
	}

	public VehicleType(Long vehicleTypeId, String type, Date created, Long version) {
		super();
		this.vehicleTypeId = vehicleTypeId;
		this.type = type;
		this.created = created;
		this.version = version;
	}

	public Long getVehicleTypeId() {
		return vehicleTypeId;
	}

	public void setVehicleTypeId(Long vehicleTypeId) {
		this.vehicleTypeId = vehicleTypeId;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

}
