/*
 * Created on 3 Jul 2017 ( Time 14:38:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.appzoneltd.lastmile.microservice.employee.entity;

import java.io.Serializable;

import javax.persistence.*;

import lombok.Data;

@Data
@Embeddable
public class UserRoleEntityKey implements Serializable {

	private static final long serialVersionUID = 1L;

	@Column(name = "role_id", nullable = false)
	private Long roleId;

	@Column(name = "user_id", nullable = false)
	private Long userId;

	// ----------------------------------------------------------------------
	// equals METHOD
	// ----------------------------------------------------------------------
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (this.getClass() != obj.getClass())
			return false;
		UserRoleEntityKey other = (UserRoleEntityKey) obj;
		// --- Attribute roleId
		if (roleId == null) {
			if (other.roleId != null)
				return false;
		} else if (!roleId.equals(other.roleId))
			return false;
		// --- Attribute userId
		if (userId == null) {
			if (other.userId != null)
				return false;
		} else if (!userId.equals(other.userId))
			return false;
		return true;
	}

	// ----------------------------------------------------------------------
	// hashCode METHOD
	// ----------------------------------------------------------------------
	public int hashCode() {
		final int prime = 31;
		int result = 1;

		// --- Attribute roleId
		result = prime * result + ((roleId == null) ? 0 : roleId.hashCode());
		// --- Attribute userId
		result = prime * result + ((userId == null) ? 0 : userId.hashCode());

		return result;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(roleId);
		sb.append("|");
		sb.append(userId);
		return sb.toString();
	}
}
