eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    
    
jsondoc:
  version: 1.0
  basePath: /buildingtype
  packages[0]: com.appzoneltd.lastmile.microservice.buildingtype.controller
  packages[1]: com.appzoneltd.lastmile.microservice.buildingtype.dao
  
server:
  port: 0
  
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lastmile
    username: postgres
    password: root
  application:
    name: BUILDINGTYPE
  jpa:
    show-sql: true
    database: default 
    hibernate:
      use-new-id-generator-mappings: false
    open-in-view: false 
    
oauth2:
  tokenServiceEndpointUrl: http://localhost:60700/u/oauth/check_token
  clientId: WEB
  clientSecret: WEB
    
logging:
  file: BuildingType.log
  level:
    com.appzoneltd.lastmile.microservice.buildingtype.service.BuildingTypeServiceImpl: error
    com.appzoneltd.lastmile.microservice.buildingtype.controller.BuildingTypeController: error