/*
 * Created on 7 Nov 2016 ( Time 13:02:27 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.appzoneltd.lastmile.microservice.ondemandrequest.dao;

public interface PickupRequestRepository {

	String SQL_SELECT_BY_ID = "SELECT pickup_request_id, pickup_request_type_id, pickup_request_type.type, DATE_PART('day', current_timestamp - requesttime::timestamp) * 24 *60 + DATE_PART('hour', current_time - requesttime::time ) * 60 + DATE_PART('minute', current_time - requesttime::time ) AS recievedfrom, requester_id, users.username, users.phone, pickuplongitude, pickuplatitude, pickupwasellocation, pickupformatedaddress, time_from, time_to, pickupdate, recipient_id, recipientname, recipientmobile, recipientlongitude, recipientlatitude, recipientwasellocation, recipientformatedaddress, recipientadditionalinfo, additionalservices, labelingtext, paymenttype, paymentmethod, description, version, hub_id, created "
			+ "FROM lastmile_request.pickup_request "
			+ "INNER JOIN lastmile_request.pickup_request_type ON pickup_request_type.pickup_request_type_id = pickup_request.pickup_request_type_id "
			+ "INNER JOIN lastmile_authorization_server.users ON users.user_id = pickup_request.requester_id "
			+ " WHERE pickup_request_id = ?";

	String SQL_INSERT = "INSERT into lastmile_request.pickup_request ( pickup_request_id, pickup_request_type_id, requesttime, requester_id, pickuplongitude, pickuplatitude, pickupwasellocation, pickupformatedaddress, time_from, time_to, pickupdate, recipient_id, recipientname, recipientmobile, recipientlongitude, recipientlatitude, recipientwasellocation, recipientformatedaddress, recipientadditionalinfo, additionalservices, labelingtext, paymenttype, paymentmethod, description ,hub_id) values ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ,? )";

	String SQL_COUNT_ALL = "SELECT COUNT(*) FROM lastmile_request.pickup_request";

	String SQL_SELECT_ALL = "SELECT pickup_request_id, pickup_request_type_id, pickup_request_type.type, DATE_PART('day', current_timestamp - requesttime::timestamp) * 24 *60 + DATE_PART('hour', current_time - requesttime::time ) * 60 + DATE_PART('minute', current_time - requesttime::time ) AS recievedfrom, requester_id, users.username, users.phone, pickuplongitude, pickuplatitude, pickupwasellocation, pickupformatedaddress, time_from, time_to, pickupdate, recipient_id, recipientname, recipientmobile, recipientlongitude, recipientlatitude, recipientwasellocation, recipientformatedaddress, recipientadditionalinfo, additionalservices, labelingtext, paymenttype, paymentmethod, description, version, hub_id, created "
			+ "FROM lastmile_request.pickup_request "
			+ "INNER JOIN lastmile_request.pickup_request_type ON pickup_request_type.pickup_request_type_id = pickup_request.pickup_request_type_id "
			+ "INNER JOIN lastmile_authorization_server.users ON users.user_id = pickup_request.requester_id ";

	String PICKUP_REQUEST_FIND_ALL_TODAY_PICKUPS = "SELECT pickup_request_id, pickup_request_type_id, pickup_request_type.type, DATE_PART('day', current_timestamp - requesttime::timestamp) * 24 *60 + DATE_PART('hour', current_time - requesttime::time ) * 60 + DATE_PART('minute', current_time - requesttime::time ) AS recievedfrom, requester_id, users.username, users.phone, pickuplongitude, pickuplatitude, pickupwasellocation, pickupformatedaddress, time_from, time_to, pickupdate, recipient_id, recipientname, recipientmobile, recipientlongitude, recipientlatitude, recipientwasellocation, recipientformatedaddress, recipientadditionalinfo, additionalservices, labelingtext, paymenttype, paymentmethod, description, hub_id, version, created "
			+ "FROM lastmile_request.pickup_request "
			+ "INNER JOIN lastmile_request.pickup_request_type ON pickup_request_type.pickup_request_type_id = pickup_request.pickup_request_type_id "
			+ "INNER JOIN lastmile_authorization_server.users ON users.user_id = pickup_request.requester_id "
			+ "WHERE pickupdate = current_date ";
}
