/*
 * Created on 7 Nov 2016 ( Time 11:23:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.appzoneltd.lastmile.microservice.ondemandrequest.dao;

import java.io.Serializable;

import java.util.Date;

import com.appzoneltd.lastmile.microservice.enums.OrderStatus;

/**
 * @author alaa.nabil
 *
 */
public class RequestHistory implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5317052820811640482L;

	private Long requestHistoryId;
	private Long packageId;
	private OrderStatus orderStatus;
	private Date created;
	private Long orderId;
	private Long version;

	public RequestHistory() {
	}

	public RequestHistory(Long requestHistoryId, Long packageId, OrderStatus orderStatus, Date created, Long orderId,
			Long version) {
		super();
		this.requestHistoryId = requestHistoryId;
		this.packageId = packageId;
		this.orderStatus = orderStatus;
		this.created = created;
		this.orderId = orderId;
		this.version = version;
	}

	public Long getRequestHistoryId() {
		return requestHistoryId;
	}

	public void setRequestHistoryId(Long requestHistoryId) {
		this.requestHistoryId = requestHistoryId;
	}

	public Long getPackageId() {
		return packageId;
	}

	public void setPackageId(Long packageId) {
		this.packageId = packageId;
	}

	public OrderStatus getOrderStatus() {
		return orderStatus;
	}

	public void setOrderStatus(OrderStatus orderStatus) {
		this.orderStatus = orderStatus;
	}

	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Long getOrderId() {
		return orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

}
