/*
 * Created on 27 Dec 2016 ( Time 16:30:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.appzoneltd.lastmile.microservice.deliveryworkflow.delegate.notification;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

@Entity
@Table(name = "pickup_request", schema = "lastmile_request")
@NamedQueries({
        @NamedQuery(name = "InvoicePickupRequestEntity.countAll", query = "SELECT COUNT(x) FROM InvoicePickupRequestEntity x")})
public class InvoicePickupRequestEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @Column(name = "pickup_request_id", nullable = false)
    private Long pickupRequestId;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "requesttime")
    private Date requesttime;

    @Column(name = "pickuplongitude", length = 50)
    private String pickuplongitude;

    @Column(name = "pickuplatitude", length = 50)
    private String pickuplatitude;

    @Column(name = "pickupwasellocation", length = 200)
    private String pickupwasellocation;

    @Column(name = "pickupformatedaddress", length = 250)
    private String pickupformatedaddress;

    @Column(name = "time_from", length = 50)
    private String timeFrom;

    @Column(name = "time_to", length = 50)
    private String timeTo;

    @Temporal(TemporalType.DATE)
    @Column(name = "pickupdate")
    private Date pickupdate;

    @Column(name = "recipientname", length = 50)
    private String recipientname;

    @Column(name = "recipientmobile", length = 20)
    private String recipientmobile;

    @Column(name = "recipientlongitude", length = 50)
    private String recipientlongitude;

    @Column(name = "recipientlatitude", length = 50)
    private String recipientlatitude;

    @Column(name = "recipientwasellocation", length = 200)
    private String recipientwasellocation;

    @Column(name = "recipientformatedaddress", length = 250)
    private String recipientformatedaddress;

    @Column(name = "recipientadditionalinfo", length = 250)
    private String recipientadditionalinfo;

    @Column(name = "pickup_service_type_id")
    private Long pickupServiceTypeId;

    @Column(name = "additionalservices", length = 200)
    private String additionalservices;

    @Column(name = "labelingtext", length = 250)
    private String labelingtext;

    @Column(name = "paymenttype", length = 100)
    private String paymenttype;

    @Column(name = "paymentmethod", length = 100)
    private String paymentmethod;

    @Column(name = "description", length = 250)
    private String description;

    @Column(name = "request_status", length = 50)
    private String requestStatus;

//    @OneToOne(mappedBy = "pickupRequest", targetEntity = PickupRequestDocumentEntity.class)
//    private PickupRequestDocumentEntity pickupRequestDocument;

    @Column(name = "version", nullable = false)
    private Long version;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created")
    private Date created;

//    @ManyToOne
//    @JoinColumn(name = "requester_id", referencedColumnName = "customer_id")
//    private CustomerEntity requester;

    @ManyToOne
    @JoinColumn(name = "pickup_request_type_id", referencedColumnName = "pickup_request_type_id")
    private PickupRequestTypeEntity pickupRequestType;

//    @ManyToOne
//    @JoinColumn(name = "recipient_id", referencedColumnName = "customer_id")
//    private CustomerEntity recipient;

//    @OneToOne(mappedBy = "pickupRequest", targetEntity = VerifiedPickupRequestEntity.class)
//    private VerifiedPickupRequestEntity verifiedPickupRequestEntity;


//    public PickupRequestEntity() {
//        super();
//    }

    public Long getPickupRequestId() {
        return this.pickupRequestId;
    }

    public void setPickupRequestId(Long pickupRequestId) {
        this.pickupRequestId = pickupRequestId;
    }

    public Date getRequesttime() {
        return this.requesttime;
    }

    public void setRequesttime(Date requesttime) {
        this.requesttime = requesttime;
    }

    public String getPickuplongitude() {
        return this.pickuplongitude;
    }

    public void setPickuplongitude(String pickuplongitude) {
        this.pickuplongitude = pickuplongitude;
    }

    public String getPickuplatitude() {
        return this.pickuplatitude;
    }

    public void setPickuplatitude(String pickuplatitude) {
        this.pickuplatitude = pickuplatitude;
    }

    public String getPickupwasellocation() {
        return this.pickupwasellocation;
    }

    public void setPickupwasellocation(String pickupwasellocation) {
        this.pickupwasellocation = pickupwasellocation;
    }

    public String getPickupformatedaddress() {
        return this.pickupformatedaddress;
    }

    public void setPickupformatedaddress(String pickupformatedaddress) {
        this.pickupformatedaddress = pickupformatedaddress;
    }

    public String getTimeFrom() {
        return this.timeFrom;
    }

    public void setTimeFrom(String timeFrom) {
        this.timeFrom = timeFrom;
    }

    public String getTimeTo() {
        return this.timeTo;
    }

    public void setTimeTo(String timeTo) {
        this.timeTo = timeTo;
    }

    public Date getPickupdate() {
        return this.pickupdate;
    }

    public void setPickupdate(Date pickupdate) {
        this.pickupdate = pickupdate;
    }

    public String getRecipientname() {
        return this.recipientname;
    }

    public void setRecipientname(String recipientname) {
        this.recipientname = recipientname;
    }

    public String getRecipientmobile() {
        return this.recipientmobile;
    }

    public void setRecipientmobile(String recipientmobile) {
        this.recipientmobile = recipientmobile;
    }

    public String getRecipientlongitude() {
        return this.recipientlongitude;
    }

    public void setRecipientlongitude(String recipientlongitude) {
        this.recipientlongitude = recipientlongitude;
    }

    public String getRecipientlatitude() {
        return this.recipientlatitude;
    }

    public void setRecipientlatitude(String recipientlatitude) {
        this.recipientlatitude = recipientlatitude;
    }

    public String getRecipientwasellocation() {
        return this.recipientwasellocation;
    }

    public void setRecipientwasellocation(String recipientwasellocation) {
        this.recipientwasellocation = recipientwasellocation;
    }

    public String getRecipientformatedaddress() {
        return this.recipientformatedaddress;
    }

    public void setRecipientformatedaddress(String recipientformatedaddress) {
        this.recipientformatedaddress = recipientformatedaddress;
    }

    public String getRecipientadditionalinfo() {
        return this.recipientadditionalinfo;
    }

    public void setRecipientadditionalinfo(String recipientadditionalinfo) {
        this.recipientadditionalinfo = recipientadditionalinfo;
    }

    public Long getPickupServiceTypeId() {
        return this.pickupServiceTypeId;
    }

    public void setPickupServiceTypeId(Long pickupServiceTypeId) {
        this.pickupServiceTypeId = pickupServiceTypeId;
    }

    public String getAdditionalservices() {
        return this.additionalservices;
    }

    public void setAdditionalservices(String additionalservices) {
        this.additionalservices = additionalservices;
    }

    public String getLabelingtext() {
        return this.labelingtext;
    }

    public void setLabelingtext(String labelingtext) {
        this.labelingtext = labelingtext;
    }

    public String getPaymenttype() {
        return this.paymenttype;
    }

    public void setPaymenttype(String paymenttype) {
        this.paymenttype = paymenttype;
    }

    public String getPaymentmethod() {
        return this.paymentmethod;
    }

    public void setPaymentmethod(String paymentmethod) {
        this.paymentmethod = paymentmethod;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getVersion() {
        return this.version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

//    public CustomerEntity getRequester() {
//        return requester;
//    }
//
//    public void setRequester(CustomerEntity requester) {
//        this.requester = requester;
//    }
//
//    public CustomerEntity getRecipient() {
//        return recipient;
//    }
//
//    public void setRecipient(CustomerEntity recipient) {
//        this.recipient = recipient;
//    }
//
    public PickupRequestTypeEntity getPickupRequestType() {
        return pickupRequestType;
    }

    public void setPickupRequestType(PickupRequestTypeEntity pickupRequestType) {
        this.pickupRequestType = pickupRequestType;
    }
//
//    public PickupRequestDocumentEntity getPickupRequestDocument() {
//        return pickupRequestDocument;
//    }
//
//    public void setPickupRequestDocument(PickupRequestDocumentEntity pickupRequestDocument) {
//        this.pickupRequestDocument = pickupRequestDocument;
//    }

    public String getRequestStatus() {
        return requestStatus;
    }

    public void setRequestStatus(String requestStatus) {
        this.requestStatus = requestStatus;
    }

//    public VerifiedPickupRequestEntity getVerifiedPickupRequestEntity() {
//        return verifiedPickupRequestEntity;
//    }
//
//    public void setVerifiedPickupRequestEntity(VerifiedPickupRequestEntity verifiedPickupRequestEntity) {
//        this.verifiedPickupRequestEntity = verifiedPickupRequestEntity;
//    }
}
