/*
 * Created on 30 Jan 2017 ( Time 11:57:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.appzoneltd.lastmile.microservice.deliveryworkflow.delegate.notification;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

@Entity
@Table(name = "verified_package", schema = "lastmile_core")
@NamedQueries({
		@NamedQuery(name = "VerifiedPackageEntity.countAll", query = "SELECT COUNT(x) FROM VerifiedPackageEntity x") })
public class VerifiedPackageEntity implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "package_id", nullable = false)
	private Long packageId;

	@Column(name = "actualweight", nullable = false)
	private BigDecimal actualweight;

	@Column(name = "description", length = 500)
	private String description;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false)
	private Date created;

	@Column(name = "version", nullable = false)
	private long version;

//	@OneToOne
//	@JoinColumn(name = "package_id", referencedColumnName = "package_id", insertable = false, updatable = false)
//	private PackageEntity pckage;

	@ManyToOne
	@JoinColumn(name = "package_type_id", referencedColumnName = "package_type_id")
	private PackageTypeEntity packageType;

//	@ManyToMany(targetEntity = StaticContentEntity.class)
//	@JoinTable(name = "verified_package_images", schema = "lastmile_core", joinColumns = @JoinColumn(name = "package_id", referencedColumnName = "package_id"), inverseJoinColumns = @JoinColumn(name = "image_id", referencedColumnName = "content_id"))
//	@LazyCollection(LazyCollectionOption.FALSE)
//	private Set<StaticContentEntity> listOfStaticContent;

	public VerifiedPackageEntity() {
		super();
		this.created = new Date();
	}

//	public VerifiedPackageEntity(Long packageId, BigDecimal actualweight, String description,
//			PackageTypeEntity packageType, Set<StaticContentEntity> listOfStaticContent) {
//		super();
//		this.created = new Date();
//		this.packageId = packageId;
//		this.actualweight = actualweight;
//		this.description = description;
//		this.packageType = packageType;
//		this.listOfStaticContent = listOfStaticContent;
//	}

	public void setPackageId(Long packageId) {
		this.packageId = packageId;
	}

	public Long getPackageId() {
		return this.packageId;
	}

	public void setActualweight(BigDecimal actualweight) {
		this.actualweight = actualweight;
	}

	public BigDecimal getActualweight() {
		return this.actualweight;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDescription() {
		return this.description;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public Long getVersion() {
		return this.version;
	}

//	public void setPackage(PackageEntity pckage) {
//		this.pckage = pckage;
//	}
//
//	public PackageEntity getPackage() {
//		return this.pckage;
//	}
//
	public void setPackageType(PackageTypeEntity packageType) {
		this.packageType = packageType;
	}

	public PackageTypeEntity getPackageType() {
		return this.packageType;
	}
//
//	public Set<StaticContentEntity> getListOfStaticContent() {
//		return listOfStaticContent;
//	}
//
//	public void setListOfStaticContent(Set<StaticContentEntity> listOfStaticContent) {
//		this.listOfStaticContent = listOfStaticContent;
//	}

}
