/*
 * Created on 15 Feb 2017 ( Time 14:52:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.appzoneltd.lastmile.microservice.distributionplan.dao;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;
import java.util.List;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

/**
 * Persistent class for entity stored in table "package_type"
 *
 * @author Telosys Tools Generator
 */

@Entity
@Table(name = "package_type", schema = "lastmile_core")
// Define named queries here
@NamedQueries({
        @NamedQuery(name = "PackageTypeEntity.countAll", query = "SELECT COUNT(x) FROM PackageTypeEntity x")
})
public class PackageTypeEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name = "package_type_id", nullable = false)
    private Long packageTypeId;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name = "packagetype", nullable = false, length = 50)
    private String packagetype;

    @Column(name = "packagedimension", nullable = false, length = 50)
    private String packagedimension;

    @Column(name = "expectedweight", nullable = false)
    private Long expectedweight;

    @Column(name = "description", length = 500)
    private String description;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created", nullable = false)
    private Date created;

    @Column(name = "version", nullable = false)
    private Long version;


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy = "packageType", targetEntity = PackageEntity.class)
    private List<PackageEntity> listOfPackage;

    @OneToMany(mappedBy = "packageType", targetEntity = VerifiedPackageEntity.class)
    private List<VerifiedPackageEntity> listOfVerifiedPackage;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public PackageTypeEntity() {
        super();
    }

    public Long getPackageTypeId() {
        return this.packageTypeId;
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setPackageTypeId(Long packageTypeId) {
        this.packageTypeId = packageTypeId;
    }

    public String getPackagetype() {
        return this.packagetype;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : packagetype ( varchar )
    public void setPackagetype(String packagetype) {
        this.packagetype = packagetype;
    }

    public String getPackagedimension() {
        return this.packagedimension;
    }

    //--- DATABASE MAPPING : packagedimension ( varchar )
    public void setPackagedimension(String packagedimension) {
        this.packagedimension = packagedimension;
    }

    public Long getExpectedweight() {
        return this.expectedweight;
    }

    //--- DATABASE MAPPING : expectedweight ( int8 )
    public void setExpectedweight(Long expectedweight) {
        this.expectedweight = expectedweight;
    }

    public String getDescription() {
        return this.description;
    }

    //--- DATABASE MAPPING : description ( varchar )
    public void setDescription(String description) {
        this.description = description;
    }

    public Date getCreated() {
        return this.created;
    }

    //--- DATABASE MAPPING : created ( timestamptz )
    public void setCreated(Date created) {
        this.created = created;
    }

    public Long getVersion() {
        return this.version;
    }

    //--- DATABASE MAPPING : version ( int8 )
    public void setVersion(Long version) {
        this.version = version;
    }

    public List<PackageEntity> getListOfPackage() {
        return this.listOfPackage;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfPackage(List<PackageEntity> listOfPackage) {
        this.listOfPackage = listOfPackage;
    }

    public List<VerifiedPackageEntity> getListOfVerifiedPackage() {
        return this.listOfVerifiedPackage;
    }

    public void setListOfVerifiedPackage(List<VerifiedPackageEntity> listOfVerifiedPackage) {
        this.listOfVerifiedPackage = listOfVerifiedPackage;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append("[");
        sb.append(packageTypeId);
        sb.append("]:");
        sb.append(packagetype);
        sb.append("|");
        sb.append(packagedimension);
        sb.append("|");
        sb.append(expectedweight);
        sb.append("|");
        sb.append(description);
        sb.append("|");
        sb.append(created);
        sb.append("|");
        sb.append(version);
        return sb.toString();
    }

}
